[package]
name = "dynlib_derive"
version = "0.1.0"
authors = ["Szymon Wieloch <szymon.wieloch@gmail.com>"]
description = "Derive macros for the dynlib crate."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
libc = "0.2.29"

