[package]
name = "dlopen_derive"
version = "0.1.0"
authors = ["Szymon Wieloch <szymon.wieloch@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
libc = "0.2.29"



[[example]]
name = "derive"
crate-type = ["bin"]
