[package]
name = "dynlib"
version = "0.1.0"
authors = ["Szymon Wieloch <szymon.wieloch@gmail.com>"]

[dependencies]

#dlopen_derive = {path = "rust-dynlib-derive"}

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.29"
lazy_static = "0.2.8"

[[example]]
name = "open_lib"
crate-type = ["bin"]