[package]
name = "dynlib"
version = "0.1.0"
authors = ["Szymon Wieloch <szymon.wieloch@gmail.com>"]
description = "A library for opening and operating on dynamically loadable libraries."
keywords = [
    #common functions
    "dlopen", "loadlibrary", "loadlibraryw",
    #common names
    "shared object", "dynamic link library",
    #other libraries that somebody may be searching for
    "dynlib", "libloading", "rust_libloading", "dynamic_reload",
    #common extensions
    "dll", "so", "dylib"]
license = "MIT"
repository = "https://github.com/szymonwieloch/rust-dynlib"

[dependencies]

dynlib_derive = {path = "rust-dynlib-derive"}

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.29"
lazy_static = "0.2.8"

[dev-dependencies]
const-cstr = "0.1"
example_dylib = {path = "rust-example-dylib"}
libc = "0.2.29"
regex = "0.2"

[[example]]
name = "raw"
crate-type = ["bin"]

[[example]]
name = "symbor"
crate-type = ["bin"]

[[example]]
name = "symbor_api"
crate-type = ["bin"]

[[example]]
name = "wrapper_api"
crate-type = ["bin"]

[[example]]
name = "wrapper_multi_api"
crate-type = ["bin"]

