[package]
name = "dlopen"
version = "0.1.0"
authors = ["Szymon Wieloch <szymon.wieloch@gmail.com>"]

[dependencies]
libc = "0.2.29"
dlopen_derive = {path = "rust-dlopen-derive"}

[[example]]
name = "open_lib"
crate-type = ["bin"]

[[example]]
name = "derive"
crate-type = ["bin"]

[[example]]
name = "test"
crate-type = ["bin"]

[[example]]
name = "dlopen"
crate-type = ["bin"]

[[example]]
name = "wrapper"
crate-type = ["bin"]

[[example]]
name = "interface"
crate-type = ["bin"]

[[example]]
name = "double"
crate-type = ["bin"]